version: '3.4'

services:
  server:
    image: server
    restart: always
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
